In [5]:
#create a numpy array of 5 zeros.
#check datatype, itemsize and shape of above
import numpy as np
a = np.zeros(5)
print(a)
print(a.dtype)
print(a.itemsize)
print(a.shape)

[0. 0. 0. 0. 0.]
float64
8
(5,)


In [7]:
#create a numpy array of ones of shape (5,4)
a = np.ones((5,4))
print(a)
print(a.dtype)
print(a.itemsize)
print(a.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float64
8
(5, 4)


In [19]:
#create a matrix of shape 4,5 with numbers from 1-20
a = np.arange(1,21).reshape(4,5)
print(a)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [22]:
#multiply all elements of above array by 10
b = a*10
print(b)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [25]:
#print odd elements from array
i = a%2 != 0
print(a)
print(i)
print(a[i])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]]
[ 1  3  5  7  9 11 13 15 17 19]


In [43]:
#replace all even elements by their negative
r = np.where(a%2 == 0, -a, a)
print(a)
print(r)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[  1  -2   3  -4   5]
 [ -6   7  -8   9 -10]
 [ 11 -12  13 -14  15]
 [-16  17 -18  19 -20]]


In [94]:
#create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
#M1 = np.arange(1,17,1).reshape(4,4)
M1 = np.linspace(1,16,16, dtype = 'int').reshape(4,4)
print(M1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [56]:
#create a transpose of above matrix call it M2
M2 = M1.T
print(M2)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [57]:
#find sum of above matrix M3 = (M1 + M2)
M3 = M1+M2
print(M3)

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]


In [62]:
#Find Transpose of M3, Call it MT1. Check if M3 == MT1
MT1 = M3.T
print(MT1)

i = M3 == MT1
print(i)

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [59]:
#find diffrence of M4 = (M1 - M2)
M4 = M1-M2
print(M4)

[[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]


In [61]:
# Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
MT2 = M4.T
print(MT2)
i = M4 == -MT2
print(i)

[[ 0  3  6  9]
 [-3  0  3  6]
 [-6 -3  0  3]
 [-9 -6 -3  0]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [117]:
# create a matrix (3x4) R1 of random numbers between 10-40
a = np.random.randint(10,40,12).reshape(3,4)
print(a)
print()
# find min and max column wise
r =  a.min(0)
print(r)
print()
r = a.max(0)
print(r)
print()
# replace the last column with sum of all the columns

r = a[:,-1]
print(r)
print()
print(r.sum())
print()
print(r.sum)
a[:,3] = r.sum()
print()
print(a)


[[15 39 24 33]
 [10 31 19 11]
 [22 24 22 20]]

[10 24 19 11]

[22 39 24 33]

[33 11 20]

64

<built-in method sum of numpy.ndarray object at 0x0000000005663B20>

[[15 39 24 64]
 [10 31 19 64]
 [22 24 22 64]]


In [118]:
# create a matrix (3x4) R1 of random numbers between 10-40
a = np.random.randint(10,40,12).reshape(3,4)
print(a)
print()
#replace all even elements with nan in R1

r = np.where(a%2 == 0, np.nan, a)
print(r)

#count number of nan in R1
print()
print(np.sum(np.isnan(r)))


[[21 18 35 25]
 [30 21 36 29]
 [15 35 15 11]]

[[21. nan 35. 25.]
 [nan 21. nan 29.]
 [15. 35. 15. 11.]]

3


In [119]:
# check output of this code
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
