## NUMPY
- create a numpy array of 5 zeros.
    - check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative
  
  
  
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns


- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1



- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`


In [2]:
import numpy as np

In [2]:
# - create a numpy array of 5 zeros.
#     - check datatype, itemsize and shape of above

arr=np.array([0,0,0,0,0])
print(arr)
# or 
arr1=np.zeros(5)
print(arr1)

print(arr.dtype)
print(arr.itemsize)
print(arr.shape)

print(arr1.dtype)
print(arr1.itemsize)
print(arr1.shape)

[0 0 0 0 0]
[ 0.  0.  0.  0.  0.]
int32
4
(5,)
float64
8
(5,)


In [3]:
# - create a numpy array of ones of shape (5,4)
a1=np.ones((5,4),dtype='int')
print(a1)
print(a1.dtype)
print(a1.itemsize)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
int32
4


In [4]:
# - create a matrix of shape 4,5 with numbers from 1-20
a2=np.arange(1,21)
print(a2)
print()
a3=a2.reshape((4,5))  # one way of doing it 
print(a3)
print()
a=np.reshape(a2,(4,5)) # anoter way of doing it
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [5]:
# - multiply all elements of above array by 10
a4=a*10
print(a4)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [6]:
# - print odd elements from array
print(a)
print()

decision= a%2==1
print(decision)
print()

odd=a[decision]
print(odd)
print()

# another way of doing above thing
odd1=a[a%2==1]
print(odd1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]]

[ 1  3  5  7  9 11 13 15 17 19]

[ 1  3  5  7  9 11 13 15 17 19]


In [7]:
# - replace all even elements by their negative
a=np.arange(1,21).reshape((4,5))
a=a*-1
print(a)

[[ -1  -2  -3  -4  -5]
 [ -6  -7  -8  -9 -10]
 [-11 -12 -13 -14 -15]
 [-16 -17 -18 -19 -20]]


In [8]:
# - create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
m1=np.linspace(1,16,16,dtype='int').reshape((4,4))
print(m1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [9]:
# - create a transpose of above matrix call it M2
m2=m1.T
print(m2)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [10]:
# - find sum of above matrix M3 = (M1 + M2)
m3=m1+m2
print(m3)

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]


In [11]:
# - Find Transpose of M3, Call it MT1. Check if M3 == MT1
mt1=m3.T
print(mt1)
print()

new= m3==mt1
print(new)
print()
if np.count_nonzero(new)==new.size:
    print("M3 and MT1 are same")


[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]

M3 and MT1 are same


In [12]:
# - find diffrence of M4 = (M1 - M2)
m4=m1-m2
print(m4)

[[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]


In [13]:
# - Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
mt2=m4.T
print(mt2)
print()

new1= m4==mt2
print(new1)
print()
if np.count_nonzero(new1)==new1.size:
    print("M4 and mt2 are same")
else:
    print("M4 and mt2 are different")
    
print()
print()

new2= m4==-mt2
print(new2)
print()
if np.count_nonzero(new2)==new2.size:
    print("M4 and -mt2 are same")
else:
    print("M4 and -mt2 are different")

[[ 0  3  6  9]
 [-3  0  3  6]
 [-6 -3  0  3]
 [-9 -6 -3  0]]

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]

M4 and mt2 are different


[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]

M4 and -mt2 are same


In [14]:
# - create a matrix (3x4) R1 of random numbers between 10-40
r1=np.random.randint(10,40,12).reshape((3,4))
print(r1)

[[36 16 27 38]
 [13 17 35 12]
 [13 22 34 34]]


In [15]:
# - find min and max column wise
print("min:  ",r1.min(axis=0))
print("max:  ",r1.max(axis=0))

min:   [13 16 27 12]
max:   [36 22 35 38]


In [16]:
# - replace the last column with sum of all the columns
s=r1.sum(axis=1)
print(s)
r1[:,3]=s
print(r1)

[117  77 103]
[[ 36  16  27 117]
 [ 13  17  35  77]
 [ 13  22  34 103]]


In [6]:
# - create a matrix (3x4) R1 of random numbers between 10-40
r1=np.random.randint(10,40,12).reshape((3,4)).astype(float)
print(r1)

[[ 30.  37.  28.  38.]
 [ 32.  25.  34.  26.]
 [ 22.  24.  22.  15.]]


In [7]:
# - replace all even elements with nan in R1

d=r2%2==0
print(d)

r2[d]=np.nan
print(r2)


[[False False  True False]
 [False False  True  True]
 [False  True  True  True]]
[[ 29.  19.  nan  17.]
 [ 13.  25.  nan  nan]
 [ 25.  nan  nan  nan]]


In [14]:
# - count number of nan in R1
na=np.isnan(r2)
print(na)
print("The count of nan values is : ",np.count_nonzero(na))

# or
print("The count of nan values is",d.sum())

[[False False  True False]
 [False False  True  True]
 [False  True  True  True]]
The count of nan values is :  6
The count of nan values is 6


In [ ]:
a1 = np.arange(1,10).reshape(3,3)
print(a1)
a2 = np.arange(11,20).reshape(3,3)
print(a2)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)