## NUMPY
- create a numpy array of 5 zeros.
    - check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative
  
  
  
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns


- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1



- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`


In [5]:
#create a numpy array of 5 zeros.
#check datatype, itemsize and shape of above

import numpy as np
a = np.zeros(5)
print(a)
print(a.dtype)
print(a.itemsize)
print(a.shape)

[0. 0. 0. 0. 0.]
float64
8
(5,)


In [7]:
#create a numpy array of ones of shape (5,4)

b = np.ones(20).reshape(5,4)
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [74]:
#create a matrix of shape 4,5 with numbers from 1-20
c = np.arange(1,21).reshape(4,5)
print(c)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [56]:
#multiply all elements of above array by 10
print(c*10)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [12]:
#print odd elements from array
print(c[c%2!=0])

[ 1  3  5  7  9 11 13 15 17 19]


In [73]:
#replace all even elements by their negative

for j in (c):
    for i in range(j.shape[0]):
        if j[i]%2==0:
            j[i]=-j[i]
        
print(c)

    

[[  1  -2   3  -4   5]
 [ -6   7  -8   9 -10]
 [ 11 -12  13 -14  15]
 [-16  17 -18  19 -20]]


In [81]:
#create a linearly spaced matrix M1 of size 4x4 having values in range 1-16

M1 = np.linspace(1,16,16).reshape(4,4)
M1

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]])

In [83]:
#create a transpose of above matrix call it M2
M2 = M1.T
M2

array([[ 1.,  5.,  9., 13.],
       [ 2.,  6., 10., 14.],
       [ 3.,  7., 11., 15.],
       [ 4.,  8., 12., 16.]])

In [84]:
# find sum of above matrix M3 = (M1 + M2)
M3 = M1 + M2
M3

array([[ 2.,  7., 12., 17.],
       [ 7., 12., 17., 22.],
       [12., 17., 22., 27.],
       [17., 22., 27., 32.]])

In [86]:
#Find Transpose of M3, Call it MT1. Check if M3 == MT1
MT1= M3.T
M3 == MT1

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [88]:
# find diffrence of M4 = (M1 - M2)
M4 = M1-M2
M4

array([[ 0., -3., -6., -9.],
       [ 3.,  0., -3., -6.],
       [ 6.,  3.,  0., -3.],
       [ 9.,  6.,  3.,  0.]])

In [89]:
#Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
MT2 = M4.T
MT2

array([[ 0.,  3.,  6.,  9.],
       [-3.,  0.,  3.,  6.],
       [-6., -3.,  0.,  3.],
       [-9., -6., -3.,  0.]])

In [90]:
M4==MT2

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [91]:
M4==-MT2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [93]:
#create a matrix (3x4) R1 of random numbers between 10-40
a_rand = np.random.randint(10,40,12).reshape(3,4)
a_rand

array([[34, 23, 29, 17],
       [22, 38, 31, 16],
       [27, 33, 26, 21]])

In [99]:
#     find min and max column wise
col_max = np.amax(a_rand,axis=0)
col_min = np.amin(a_rand, axis = 0)
print(col_max,col_min)







[34 38 31 21] [22 23 26 16]


In [105]:
#     replace the last column with sum of all the columns
a_rand[:,3]= a_rand[:,0]+a_rand[:,1]+a_rand[:,2]
print(a_rand)

[[34 23 29 86]
 [22 38 31 91]
 [27 33 26 86]]


In [127]:
#     create a matrix (3x4) R1 of random numbers between 10-40
R1 = np.random.randint(10,40,12).reshape(3,4)
print(R1)

[[24 14 17 37]
 [30 10 12 16]
 [25 19 33 38]]


In [122]:
#     replace all even elements with nan in R1
R1 = R1.astype('float64')
print(R1.dtype)
R1[R1%2==0]= np.NaN
print(R1)

float64
[[nan nan 25. nan]
 [23. 33. 15. 27.]
 [nan 21. 23. 13.]]


C:\Users\panini\anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in remainder
  after removing the cwd from sys.path.


In [126]:
#     count number of nan in R1
R2 = np.isnan(R1)
np.sum(np.sum(R2, axis=1))

4

In [129]:
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
