In [5]:
import numpy as np

In [33]:
# Q1. create a numpy array of 5 zeros.
#     check datatype, itemsize and shape of above

import numpy as np

a = np.array([0,0,0,0,0]) 

print('Numpy Array is: ',a)
print()
print('Data Type: ',a.dtype)
print('Item Size: ',a.itemsize)
print('Dimensions: ',a.shape)


Numpy Array is:  [0 0 0 0 0]

Data Type:  int32
Item Size:  4
Dimensions:  (5,)


In [31]:
# Q2. create a numpy array of ones of shape (5,4).

a = np.array([[1,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1]])
a.shape = (5,4)
print(a)
print()
print('Dimensions of Numpy array is: ',a.shape)


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

Dimensions of Numpy array is:  (5, 4)


In [49]:
# Q3. create a matrix of shape 4,5 with numbers from 1-20

b = np.arange(1,21)
print('Elements of Matrix are: ',b)
print()

b.shape = (4,5)
print(b)
print()
print('Dimensions of above Matrix is: ',b.shape)


Elements of Matrix are:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Dimensions of above Matrix is:  (4, 5)


In [50]:
# Q4. multiply all elements of above array by 10

b = b*10
print('Matrix after multiplying with 10:')
print(b)


Matrix after multiplying with 10:
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [51]:
# Q5. print odd elements from array

b = np.arange(1,21,2)
print('Odd Elements are: ',b)


Odd Elements are:  [ 1  3  5  7  9 11 13 15 17 19]


In [124]:
# Q6. replace all even elements by their negative

b = np.arange(1,21)
print('Input: ',b)
print()
print('After replacing Even numbers to their negatives: ')
print(np.where(b%2==0,-1*b,b))



Input:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

After replacing Even numbers to their negatives: 
[  1  -2   3  -4   5  -6   7  -8   9 -10  11 -12  13 -14  15 -16  17 -18
  19 -20]


In [130]:
# Q7. create a linearly spaced matrix M1 of size 4x4 having values in range 1-16

c = np.linspace(1,16,16).reshape(4,4)
print('Linearly spaced matrix M1 of size 4x4 is: ')
print()
print(c)


Linearly spaced matrix M1 of size 4x4 is: 

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [88]:
# Q8. create a transpose of above matrix call it M2


print('The original Matrix M1 is:')
print(c)                           # c = M1 and d = M2
print()
d = np.transpose(c)
print('Transposed Matrix M2 is:') 
print(d) 


The original Matrix M1 is:
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]

Transposed Matrix M2 is:
[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]


In [89]:
# Q9. find sum of above matrix M3 = (M1 + M2)

print('M1 matrix is: ')
print(c)
print()
print('M2 matrix is: ')
print(d)
print()

print('Sum of 2 matrices M3 is: ')
e = np.add(c,d)
print(e)


M1 matrix is: 
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]

M2 matrix is: 
[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]

Sum of 2 matrices M3 is: 
[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]


In [90]:
# Q10. Find Transpose of M3, Call it MT1. Check if M3 == MT1

print('M3 matrix is: ')
print(e)
print()

f = np.transpose(e)
print('Transposed Matrix MT1 is:') 
print(f) 

# Observation: M3 == MT1 as row & column wise we have same elements.


M3 matrix is: 
[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]

Transposed Matrix MT1 is:
[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]


In [91]:
# Q11. find diffrence of M4 = (M1 - M2)

print('M1 matrix is: ')
print(c)
print()
print('M2 matrix is: ')
print(d)
print()

print('Difference of 2 matrices M4 is: ')
g = np.subtract(c,d)
print(g)


M1 matrix is: 
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]

M2 matrix is: 
[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]

Difference of 2 matrices M4 is: 
[[ 0. -3. -6. -9.]
 [ 3.  0. -3. -6.]
 [ 6.  3.  0. -3.]
 [ 9.  6.  3.  0.]]


In [104]:
# Q12. Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2

print('M4 matrix is: ')
print(g)
print()

h = np.transpose(g)
print('Transposed Matrix MT2 is:') 
print(h) 

# Observation: M4 == MT2 as row & column wise we have same elements.


M4 matrix is: 
[[ 0. -3. -6. -9.]
 [ 3.  0. -3. -6.]
 [ 6.  3.  0. -3.]
 [ 9.  6.  3.  0.]]

Transposed Matrix MT2 is:
[[ 0.  3.  6.  9.]
 [-3.  0.  3.  6.]
 [-6. -3.  0.  3.]
 [-9. -6. -3.  0.]]


In [134]:
# Q13. create a matrix (3x4) R1 of random numbers between 10-40

R1 = np.random.randint(10,40,size=(3,4))
print('(3x4) Matrix of random numbers between 10-40 is: ')
print()
print(R1)


(3x4) Matrix of random numbers between 10-40 is: 

[[14 25 30 28]
 [19 10 33 35]
 [30 20 12 16]]


In [131]:
# Q14. find min and max column wise

print('Matrix is: ')
print(c)
print()

print('    Column wise   ')
print('    ============  ')

j = np.max(c, axis=0)
print('Max Value: ',j)

k = np.min(c, axis=0)
print('Min Value: ',k)


Matrix is: 
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]

    Column wise   
Max Value:  [13. 14. 15. 16.]
Min Value:  [1. 2. 3. 4.]


In [132]:
# Q15. replace the last column with sum of all the columns

print('Matrix is: ')
print(c)
print()

print('Last Column is: ')
print(c[:,-1])
print()

print('Sum of all elements in last column is: ')
print(c.sum())
print()

print('After replacing the last column with sum of all the columns: ')
c[:,3]=c.sum()
print(c)


Matrix is: 
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]

Last Column is: 
[ 4.  8. 12. 16.]

Sum of all elements in last column is: 
136.0

After replacing the last column with sum of all the columns: 
[[  1.   2.   3. 136.]
 [  5.   6.   7. 136.]
 [  9.  10.  11. 136.]
 [ 13.  14.  15. 136.]]


In [133]:
# Q16. create a matrix (3x4) R1 of random numbers between 10-40 
# Repeated question #

l = np.random.randint(10,40,size=(3,4))
print('(3x4) Matrix of random numbers between 10-40 is: ')
print()
print(l)


(3x4) Matrix of random numbers between 10-40 is: 

[[21 21 31 27]
 [16 30 30 13]
 [33 36 16 21]]


In [136]:
# Q17. replace all even elements with nan in R1

print('R1 Matrix is: ')
print(R1)
print()

R2 = np.where(R1%2 == 0, np.nan, R1)
print('Replacing all Even elements with nan in R1: ')
print(R2)


R1 Matrix is: 
[[14 25 30 28]
 [19 10 33 35]
 [30 20 12 16]]

Replacing all Even elements with nan in R1: 
[[nan 25. nan nan]
 [19. nan 33. 35.]
 [nan nan nan nan]]


In [137]:
# Q18. count number of nan in R1

print('R1 Matrix is: ')
print(R1)
print()

m = np.sum(np.isnan(R2))
print('Total number of nan in R1 is: ',m)


R1 Matrix is: 
[[14 25 30 28]
 [19 10 33 35]
 [30 20 12 16]]

Total number of nan in R1 is:  8


In [142]:
# Q19. check output of this code
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)

# print(a1) - contains 1-9 in 3x3 
# print(a2) - contains 11-19 in 3x3

a3 = np.append(a1,a2)
print(a3)

# Observation: In a3 - Values are getting appended as [ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
# ------------------------------------------------------------------------------------------------
a3 = np.append(a1,a2, axis = 0)
print(a3)

# Observation: In a3 - Values are getting appended only column wise since axis = 0 is given
# ------------------------------------------------------------------------------------------------
a3 = np.append(a1,a2, axis = 1)
print(a3)

# Observation: In a3 - Values are getting appended only row wise since axis = 1 is given


[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
