In [43]:
# NUMPY
# create a numpy array of 5 zeros.
# check datatype, itemsize and shape of above
# create a numpy array of ones of shape (5,4)
# create a matrix of shape 4,5 with numbers from 1-20
# multiply all elements of above array by 10
# print odd elements from array
# replace all even elements by their negative
# create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
# create a transpose of above matrix call it M2
# find sum of above matrix M3 = (M1 + M2)
# Find Transpose of M3, Call it MT1. Check if M3 == MT1
# find diffrence of M4 = (M1 - M2)
# Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
# create a matrix (3x4) R1 of random numbers between 10-40
# find min and max column wise
# replace the last column with sum of all the columns
# create a matrix (3x4) R1 of random numbers between 10-40
# replace all even elements with nan in R1
# count number of nan in R1
# check output of this code
# a1 = np.arange(1,10).reshape(3,3)
# a2 = np.arange(11,20).reshape(3,3)
# a3 = np.append(a1,a2)
# print(a3)
# a3 = np.append(a1,a2, axis = 0)
# print(a3)
# a3 = np.append(a1,a2, axis = 1)
# print(a3)

import numpy as np
a = np.zeros(5)
print(a, type(a), a.itemsize, a.shape)


[0. 0. 0. 0. 0.] <class 'numpy.ndarray'> 8 (5,)


In [46]:
# create a numpy array of ones of shape (5,4)
import numpy as np
a = np.ones((5,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [53]:
# create a matrix of shape 4,5 with numbers from 1-20
a=np.arange(1,21).reshape(4,5)
print(a)
# multiply all elements of above array by 10
b=a*10
print()
print(b)
# print odd elements from array
c = a % 2 != 0
print()
print(a[c])
# replace all even elements by their negative
c = a % 2 == 0
print()
print(a[c]*-1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]

[ 1  3  5  7  9 11 13 15 17 19]

[ -2  -4  -6  -8 -10 -12 -14 -16 -18 -20]


In [63]:
# create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
m1=np.arange(1,17).reshape(4,4)
print(m1)
# create a transpose of above matrix call it M2
m2=m1.T
print()
print(m2)
# find sum of above matrix M3 = (M1 + M2)
m3 = m1 + m2
print()
print(m3)
# Find Transpose of M3, Call it MT1. Check if M3 == MT1
mt1 = m3.T
print()
print(mt1)
print()
print(m3==mt1)
# find diffrence of M4 = (M1 - M2)
m4 = m1 - m2
print()
print(m4)
# Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
mt2=m4.T
print("mt2")
print(mt2)
print("M4 == MT2")
print( m4 == mt2)
print("M4 == -MT2")
print(m4 == -mt2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]

[[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]
mt2
[[ 0  3  6  9]
 [-3  0  3  6]
 [-6 -3  0  3]
 [-9 -6 -3  0]]
M4 == MT2
[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]
M4 == -MT2
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [79]:
# create a matrix (3x4) R1 of random numbers between 10-40
r1 = np.random.randint(10,40,12).reshape(3,4)
print(r1)
# find min and max column wise
print()
print(np.min(r1, axis=0), np.max(r1, axis=0))
# replace the last column with sum of all the columns
print()
print(r1[:,3])
r1[:,3] = r1.sum(axis=1)
print()
print(r1)

[[19 35 20 18]
 [16 29 30 37]
 [17 11 23 14]]

[16 11 20 14] [19 35 30 37]

[18 37 14]

[[ 19  35  20  92]
 [ 16  29  30 112]
 [ 17  11  23  65]]


In [110]:
# create a matrix (3x4) R1 of random numbers between 10-40

r1 = np.random.uniform(10,40, size=(3,4))
r1=np.round(r1,0)
print(r1)
# replace all even elements with nan in R1
i = r1 % 2 == 0 
print(i)
r1[i]=np.nan
# count number of nan in R1
print()
print(r1)
print()
print(np.count_nonzero(np.isnan(r1)))
print()
print(np.count_nonzero(~np.isnan(r1)))


[[33. 12. 31. 27.]
 [19. 32. 13. 17.]
 [39. 12. 13. 19.]]
[[False  True False False]
 [False  True False False]
 [False  True False False]]

[[33. nan 31. 27.]
 [19. nan 13. 17.]
 [39. nan 13. 19.]]

3

9


In [113]:
# check output of this code
a1 = np.arange(1,10).reshape(3,3)
print(a1)
a2 = np.arange(11,20).reshape(3,3)
print(a2)
a3 = np.append(a1,a2)
print()
print(a3)
a3 = np.append(a1,a2, axis = 0)
print()
print(a3)
a3 = np.append(a1,a2, axis = 1)
print()
print(a3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
