# NUMPY
- create a numpy array of 5 zeros.
    - check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative
  
  
  
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns


- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1



- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`


In [7]:
import numpy as np
a=np.zeros(5,dtype=np.int32)
print(a)
print(a.dtype)
print(a.shape)
print(a.itemsize)

[0 0 0 0 0]
int32
(5,)
4


In [12]:
a=np.ones((5,4),dtype=np.int32)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [14]:
a=np.arange(1,21).reshape(4,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [16]:
r=a*10
print(r)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [22]:
i=(a%2==1)
print(a[i])

[[ 1  3  5  7  9]
 [11 13 15 17 19]]


In [24]:
i=(a%2==0)
r=-a[i]
print(r.reshape(2,5))

[[ -2  -4  -6  -8 -10]
 [-12 -14 -16 -18 -20]]


In [26]:
M1=np.arange(1,17)
M1.resize(4,4)
print(M1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [28]:
M2=M1.T
print(M2)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [31]:
M3=M1+M2
print(M3)

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]


In [34]:
MT1=M3.T
print(MT1)
#yes they're equal

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]


In [35]:
M4=M1-M2
print(M4)

[[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]


In [37]:
MT2=M4.T
print(MT2)
#yes M4 == -MT2

[[ 0  3  6  9]
 [-3  0  3  6]
 [-6 -3  0  3]
 [-9 -6 -3  0]]


In [99]:
R1=np.random.randint(1,41,size=12)
R1.resize(3,4)
print(R1)

[[ 3 24  6 31]
 [21 37 24 24]
 [11 33 35 30]]


In [100]:
print(np.max(R1,axis=0))
print(np.min(R1,axis=0))

[21 37 35 31]
[ 3 24  6 24]


In [109]:
a=np.sum(R1,axis=0)
print(R1)
b=np.row_stack((a,R1))
c=b.T
print(c)

[[ 3 24  6 31]
 [21 37 24 24]
 [11 33 35 30]]
[[35  3 21 11]
 [94 24 37 33]
 [65  6 24 35]
 [85 31 24 30]]


In [89]:
R1=np.random.randint(10,41,size=12)
a=R1.reshape(3,4).astype(float)
print(a)

[[15. 37. 17. 32.]
 [19. 10. 30. 38.]
 [35. 18. 33. 16.]]


In [97]:
i=a%2==0
a[i]=np.nan
print(a)
b=np.isnan(a)
print(b.sum())

[[15. 37. 17. nan]
 [19. nan nan nan]
 [35. nan 33. nan]]
6


C:\Users\rohan\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in remainder
  """Entry point for launching an IPython kernel.


In [73]:
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [ ]:
# #the end
