In [1]:
import numpy as np

In [6]:
a = [10,20]
r = np.array(a)
print(r, type(r), r.dtype)
print(a, type(a))

[10 20] <class 'numpy.ndarray'> int32
[10, 20] <class 'list'>


In [7]:
r = np.array(range(10))
print(r)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
r = np.array(range(10))
print(r)
print(dir(r))

[0 1 2 3 4 5 6 7 8 9]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfl

In [ ]:
a = np.array([10,20,30,40, 55,54])
print(a.dtype)
print(a.ndim)
print(a.size)
print(a.shape)
print(a.itemsize)

In [16]:
a = [[10,20,30,40]] # 2 d: a matrix having only one row : (1,4)
b = [10,20,30,40]   # 1-d : vector                      : (4,)
c = [10,
     20,
     30,
     40]
a = [[10,20,30,40]] # 2 d: a matrix having only one row : (1,4)

In [15]:
x =  (1)
print(type(x))

<class 'int'>


In [18]:
a = np.array([[10,20,30],[10,40,49]])
print(a.shape)
print(a)

(2, 3)
[[10 20 30]
 [10 40 49]]


In [2]:
a = np.array([10,20,30,40, 55,54], dtype=np.int8)
print(a)
print(a.dtype)
print(a.ndim)
print(a.itemsize)

print()
a = np.array([10,20,30,40, 55,54], dtype='float32')
print(a)
print(a.dtype)
print(a.ndim)
print(a.itemsize)


print()
a = np.array([10.0,20,30,40, 55,54])
print(a)
print(a.dtype)
print(a.ndim)
print(a.itemsize)

[10 20 30 40 55 54]
int8
1
1

[10. 20. 30. 40. 55. 54.]
float32
1
4

[10. 20. 30. 40. 55. 54.]
float64
1
8


In [28]:

print()
a = np.array(['a', 'ab', 'abc'])
print(a)
print(a.dtype)
print(a.ndim)
print(a.itemsize)


['a' 'ab' 'abc']
<U3
1
12


In [29]:
a = np.array(['a', 'ab', 'abc', 100])
print(a)
print(a.dtype)
print(a.ndim)
print(a.itemsize)

['a' 'ab' 'abc' '100']
<U3
1
12


In [31]:
a = np.array([100, 200, [] ])
print(a)
print(a.dtype)
print(a.ndim)
print(a.itemsize)

[100 200 list([])]
object
1
8


In [4]:
a = np.arange(1,10)
print(a)
print(a.dtype)
print(a.ndim)
print(a.itemsize)

print()
a = np.arange(1,10, 2)
print(a)
print(a.dtype)
print(a.ndim)
print(a.itemsize)

[1 2 3 4 5 6 7 8 9]
int32
1
4

[1 3 5 7 9]
int32
1
4


In [8]:
print(1-1)
print("1" - "1")

0


TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [12]:
a = np.arange(1,10, 2)
print(a)
print(a.sum())
print(a.min())
print(a.max())
print(a.mean())

[1 3 5 7 9]
25
1
9
5.0


In [34]:
# from np import random
# random.randint(10)
a = np.random.randint(100)
print(a)
a = np.random.randint(100,200)
print(a)
a = np.random.randint(1, 100, 10)
print(a)

print(dir(np))
print(a)


40
183
[68 81 41 47 46 71 25 74 13 24]
['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_glob

In [41]:
a = np.arange(10,20)
print(a)

print(a[3])
print(a[3:8]) # numpy : don't go till end
print(a[3:])
print(a[3::2])
print(a[::2])

[10 11 12 13 14 15 16 17 18 19]
13
[13 14 15 16 17]
[13 14 15 16 17 18 19]
[13 15 17 19]
[10 12 14 16 18]


In [52]:
a = np.arange(10,20)
print(a)
print(a[ [2,4,9] ])
print(a.shape)

print()
i = np.random.choice(a.shape[0], size=5)
print(i)
print(a[ i ])

[10 11 12 13 14 15 16 17 18 19]
[12 14 19]
(10,)

[7 0 3 8 3]
[17 10 13 18 13]


In [55]:
a = np.linspace(10,20, 10)
print(a)

[10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ]


In [64]:
a =  np.ones((10,2))
print(a)


print();print()
a =  np.ones((3,2, 4))
print(a*2)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


[[[2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]]]


In [67]:
print(np.zeros(10,dtype = 'int8'))

[0 0 0 0 0 0 0 0 0 0]


In [77]:
a = np.arange(0,12)
print(a)

#r = a.reshape(3,5)
r = a.reshape(3,4)
print()
print(r)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [78]:
a = np.arange(0,12)
print(a)

r = a.resize(3,4)
print()
print(r)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

None
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [80]:
a = np.arange(0,12)
print(a)

a.resize(3,6)
print()
print(a)

a.resize(3,2)
print()
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [ 0  0  0  0  0  0]]

[[0 1]
 [2 3]
 [4 5]]


In [84]:
a = np.arange(0,12)
print(a)

a.resize(3,4)
print()
print(a)
print()
print(a.T)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [94]:
a = np.arange(0,12).reshape(3,4)
print(a)
# get value 5
# get row [1]  => [ 4  5  6  7]
# get last column => [3,7,11]

print()
print(a[1,1])

print()
print(a[1])
print(a[1,:])

print()
print(a[:,3])
print(a[:,-1])
print(a[:,3:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

5

[4 5 6 7]
[4 5 6 7]

[ 3  7 11]
[ 3  7 11]
[[ 3]
 [ 7]
 [11]]


In [95]:
a = np.arange(0,12).reshape(3,4)
print(a)

print()
print(a[1, 1:3])

print()
print(a[:2, 1:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[5 6]

[[1 2]
 [5 6]]


# operations

In [100]:
a = np.arange(0,12).reshape(3,4)
print(a)

print()
b = a*10 # ndarray with scalar
print(b)


print()
b = a - 10 # ndarray with scalar
print(b)


print()
b = a ** 10 # ndarray with scalar
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]

[[-10  -9  -8  -7]
 [ -6  -5  -4  -3]
 [ -2  -1   0   1]]

[[         0          1       1024      59049]
 [   1048576    9765625   60466176  282475249]
 [1073741824 -808182895 1410065408  167620825]]


In [107]:
a = np.arange(0,12).reshape(3,4)
print(a)
b = np.arange(22,10, -1).reshape(3,4)
print(b)

c = np.arange(22,10, -1).reshape(4,3)
print(c)

print()
print(b - a)

print()
print(b * a)

print()
print(b * a)

print()
print(a*c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[22 21 20 19]
 [18 17 16 15]
 [14 13 12 11]]
[[22 21 20]
 [19 18 17]
 [16 15 14]
 [13 12 11]]

[[22 20 18 16]
 [14 12 10  8]
 [ 6  4  2  0]]

[[  0  21  40  57]
 [ 72  85  96 105]
 [112 117 120 121]]

[[  0  21  40  57]
 [ 72  85  96 105]
 [112 117 120 121]]



ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [112]:
a = np.arange(0,12).reshape(3,4)
print(a)

#  b = np.arange(10,14) # this won't broadcast together
b = np.arange(10,14)
print(b)

print()
print(b - a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[10 11 12 13]

[[10 10 10 10]
 [ 6  6  6  6]
 [ 2  2  2  2]]


In [113]:
b = np.arange(10,14)
print(b)
print(b.T)

[10 11 12 13]
[10 11 12 13]


In [114]:
a = np.random.randint(-10,10,12).reshape(3,4)
print(a)

[[-3 -1  7  3]
 [ 2  9 -1  6]
 [-1 -5 -3  2]]


In [124]:
i = a > 0
print(a)
print()
print(i)
print(a.shape)
print(i.shape)

print()
print(a[i])
print(a[~i]) # negation of boolean data

[[-3 -1  7  3]
 [ 2  9 -1  6]
 [-1 -5 -3  2]]

[[False False  True  True]
 [ True  True False  True]
 [False False False  True]]
(3, 4)
(3, 4)

[7 3 2 9 6 2]
[-3 -1 -1 -1 -5 -3]


In [123]:
i = (a > -2) & (a < 5) # bit wise and
print(a)
print(a.shape)
print()
print(i)
print(i.shape)

print()
print(a[i])

[[-3 -1  7  3]
 [ 2  9 -1  6]
 [-1 -5 -3  2]]
(3, 4)

[[False  True False  True]
 [ True False  True False]
 [ True False False  True]]
(3, 4)

[-1  3  2 -1 -1  2]


In [126]:
i = (a % 2 == 0) | (a % 3 == 0) # bit wise or
print(a)
print(a.shape)
print()
print(i)
print(i.shape)

print()
print(a[i])

[[-3 -1  7  3]
 [ 2  9 -1  6]
 [-1 -5 -3  2]]
(3, 4)

[[ True False False  True]
 [ True  True False  True]
 [False False  True  True]]
(3, 4)

[-3  3  2  9  6 -3  2]


In [ ]:
Name     , Age
gaurav   , 10
krishna  , -10
abhishek1,
         , 1000

In [130]:
print(np.nan) # float
print(None)

nan
None


In [141]:
print(np.nan > np.nan)
print(np.nan < np.nan)
print(np.nan == np.nan)
print(np.nan + np.nan)
print(np.nan + 1)
print(np.nan * 1)

print()
a = np.array([ [1,2] , [10, np.nan] ])
print(a)
print(a.sum()) # pandas this is different

False
False
False
nan
nan
nan

[[ 1.  2.]
 [10. nan]]
nan


In [153]:
print(a.max())

print()
print(a.max(axis = 0)) # column wise max

print()
print(a.max(axis = 1)) # row wise max

nan

[10. nan]

[ 2. nan]


In [150]:
print(np.isnan(a))

print()
print(a == np.nan)

[[False False]
 [False  True]]

[[False False]
 [False False]]
