## NUMPY
- create a numpy array of 5 zeros.
    - check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative
  
  
  
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns


- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1



- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`


In [73]:
import numpy as np


In [74]:

#create a numpy array of 5 zeros.
#check datatype, itemsize and shape of above

print(a)
print(a.dtype)
print(a.itemsize)
print(a.shape)

[0. 0. 0. 0. 0.]
float64
8
(5,)


In [75]:
#create a numpy array of ones of shape (5,4)
b=np.ones((5,4))
print(b)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [76]:
#create a matrix of shape 4,5 with numbers from 1-20
c=np.arange(1,21).reshape(4,5)
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [77]:
#multiply all elements of above array by 10
print(c*10)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [78]:
#print odd elements from array
print(c[c%2!=0])

[ 1  3  5  7  9 11 13 15 17 19]


In [79]:
#replace all even elements by their negativea= np.zeros(5)
print(np.where(c%2==0,-c,c))

[[  1  -2   3  -4   5]
 [ -6   7  -8   9 -10]
 [ 11 -12  13 -14  15]
 [-16  17 -18  19 -20]]


In [80]:
M1=np.linspace(1,17,num=16).reshape(4,4)
print(M1)

[[ 1.          2.06666667  3.13333333  4.2       ]
 [ 5.26666667  6.33333333  7.4         8.46666667]
 [ 9.53333333 10.6        11.66666667 12.73333333]
 [13.8        14.86666667 15.93333333 17.        ]]


In [81]:
M2=M1.T
print(M2)

[[ 1.          5.26666667  9.53333333 13.8       ]
 [ 2.06666667  6.33333333 10.6        14.86666667]
 [ 3.13333333  7.4        11.66666667 15.93333333]
 [ 4.2         8.46666667 12.73333333 17.        ]]


In [82]:
M3=M1+M2
print(M3)

[[ 2.          7.33333333 12.66666667 18.        ]
 [ 7.33333333 12.66666667 18.         23.33333333]
 [12.66666667 18.         23.33333333 28.66666667]
 [18.         23.33333333 28.66666667 34.        ]]


In [83]:
MT1=M3.T
print(M3==MT1)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [84]:
M4=M1-M2
print(M4)

[[ 0.  -3.2 -6.4 -9.6]
 [ 3.2  0.  -3.2 -6.4]
 [ 6.4  3.2  0.  -3.2]
 [ 9.6  6.4  3.2  0. ]]


In [85]:
MT2=M4.T
print(MT2==M4)
print()
print(MT2==-M4)

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [86]:
#find min and max column wise

r=np.random.randint(10,30,size=12).reshape(3,4)
print(r)

[[11 13 28 27]
 [15 29 29 19]
 [27 11 11 27]]


In [87]:

print(np.max(r,axis=0))

[27 29 29 27]


In [88]:
#replace the last column with sum of all the columns
s=np.sum(r,axis=1)
print(s)
r[:,3]= s
print(r)

[79 92 76]
[[11 13 28 79]
 [15 29 29 92]
 [27 11 11 76]]


In [89]:
#create a matrix (3x4) R1 of random numbers between 10-40
r1=np.random.randint(10,30,size=12).reshape(3,4)
print(r1)

[[17 23 17 26]
 [13 28 25 18]
 [15 12 16 11]]


In [90]:
#replace all even elements with nan in R1
n =np.where(r1%2==0,np.nan,r1)
print(n)

[[17. 23. 17. nan]
 [13. nan 25. nan]
 [15. nan nan 11.]]


In [91]:
#count number of nan in R1
print(np.isnan(n).sum())

5


In [92]:
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
