## NUMPY
- create a numpy array of 5 zeros.
    - check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative
  
  
  
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns


- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1



- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`


In [1]:
import numpy as np

In [3]:
# create a numpy array of 5 zeros.
# check datatype, itemsize and shape of above
ar = np.zeros(5)
print(ar)
print(ar.dtype)
print(ar.itemsize)
print(ar.shape)

[0. 0. 0. 0. 0.]
float64
8
(5,)


In [4]:
# create a numpy array of ones of shape (5,4)
b = np.ones(20).reshape(5,4)
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
# create a matrix of shape 4,5 with numbers from 1-20
m = np.arange(1,21).reshape(4,5)
print(m)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [6]:
# multiply all elements of above array by 10
print(m*10)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [13]:
# print odd elements from array
print(m[m%2 != 0])

[ 1  3  5  7  9 11 13 15 17 19]


In [15]:
# replace all even elements by their negative
print(np.where(m%2==0,-1*m,m))

[[  1  -2   3  -4   5]
 [ -6   7  -8   9 -10]
 [ 11 -12  13 -14  15]
 [-16  17 -18  19 -20]]


In [18]:
# create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
M1 = np.linspace(1,16,16).reshape(4,4)
print(M1)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [20]:
# create a transpose of above matrix call it M2
M2 = M1.T
print(M2)

[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]


In [22]:
# find sum of above matrix M3 = (M1 + M2)
M3 = M1+M2
print(M3)

[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]


In [23]:
# Find Transpose of M3, Call it MT1. Check if M3 == MT1
MT1 = M3.T
print(M3==MT1)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [24]:
# find diffrence of M4 = (M1 - M2)
M4 = M1-M2
print(M4)

[[ 0. -3. -6. -9.]
 [ 3.  0. -3. -6.]
 [ 6.  3.  0. -3.]
 [ 9.  6.  3.  0.]]


In [25]:
# Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
MT2 = M4.T
print(M4)
print(M4 == MT2)

[[ 0. -3. -6. -9.]
 [ 3.  0. -3. -6.]
 [ 6.  3.  0. -3.]
 [ 9.  6.  3.  0.]]
[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]


In [27]:
# create a matrix (3x4) R1 of random numbers between 10-40
R1 = np.random.randint(10,40,12).reshape(3,4)
print(R1)

[[38 35 37 11]
 [38 13 35 10]
 [16 19 20 18]]


In [29]:
# find min and max column wise
print(R1.min(axis = 0))
print(R1.max(axis = 0))

[16 13 20 10]
[38 35 37 18]


In [30]:
# replace the last column with sum of all the columns
R1[:,3] = R1[:,0]+R1[:,1]+R1[:,2]
print(R1)

[[ 38  35  37 110]
 [ 38  13  35  86]
 [ 16  19  20  55]]


In [31]:
# create a matrix (3x4) R1 of random numbers between 10-40
R1 = np.random.randint(10,40,12).reshape(3,4)
print(R1)

[[13 31 11 31]
 [31 29 11 10]
 [37 23 12 25]]


In [41]:
# replace all even elements with nan in R1
R1 = np.where(R1%2==0,np.NaN,R1)
print(R1)

[[13. 31. 11. 31.]
 [31. 29. 11. nan]
 [37. 23. nan 25.]]


In [42]:
# count number of nan in R1
res=np.isnan(R1).sum()
print(res)

2


In [45]:
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
print()
a3 = np.append(a1,a2, axis = 0)
print(a3)
print()
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
