## NUMPY
- create a numpy array of 5 zeros.
    - check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative
  
  
  
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns


- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1



- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`


In [4]:
# create a numpy array of 5 zeros.
# check datatype, itemsize and shape of above
import numpy as np
# lst = [0,0,0,0,0]
# a= np.array(lst)
a = np.zeros(5)
print(a)
print(a.dtype)
# print(a.ndim)
# print(a.size)
print(a.shape)
print(a.itemsize)


[0. 0. 0. 0. 0.]
float64
(5,)
8


In [14]:
# create a numpy array of ones of shape (5,4)

a = np.arange(1,21).reshape(5,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [15]:
# create a matrix of shape 4,5 with numbers from 1-20

a = np.arange(1,21).reshape(4,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [16]:
# multiply all elements of above array by 10
print(10*a)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [19]:
# print odd elements from array
a = np.arange(1,21)
print(a)
i = a % 2 != 0
print(i)

print(a[i])


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False]
[ 1  3  5  7  9 11 13 15 17 19]


In [26]:
# replace all even elements by their negative
a = np.arange(1,21)
print(a)
print(np.where(a%2==0,-1*a,a))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  1  -2   3  -4   5  -6   7  -8   9 -10  11 -12  13 -14  15 -16  17 -18
  19 -20]


In [5]:
# create a linearly spaced matrix M1 of size 4x4 having values in range 1-16

M1 = np.linspace(1,16,16).reshape(4,4)
print(a)

[0. 0. 0. 0. 0.]


In [6]:
# create a transpose of above matrix call it M2
M2= M1.T
print(M2)

[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]


In [39]:
# find sum of above matrix M3 = (M1 + M2)
M3 = M1 + M2
print(M3)

[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]


In [46]:
# Find Transpose of M3, Call it MT1. Check if M3 == MT1
MT1 = M3.T
comparison = M3 == MT1

if comparison.all() == True:
    print("Value matched")
else:
    print("Not Matched")

Value matched


In [7]:
# find diffrence of M4 = (M1 - M2)
M4 = M1 - M2
print(M4)

[[ 0. -3. -6. -9.]
 [ 3.  0. -3. -6.]
 [ 6.  3.  0. -3.]
 [ 9.  6.  3.  0.]]


In [1]:
# Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
MT2 = M4.T

# compare1 = M4 == MT2
# print(compare1.all())

print(np.array_equal(M4,MT2))

compare2 = M4 == -MT2
print(compare2.all())

NameError: name 'M4' is not defined

In [76]:
# create a matrix (3x4) R1 of random numbers between 10-40
R1 = np.random.randint(10,40,12).reshape(3,4)
print(R1)

[[21 16 28 19]
 [16 36 34 11]
 [28 31 35 33]]


In [77]:
# find min and max column wise
print(R1.min(axis = 0)) # Min column wise max
print(R1.max(axis = 0)) # Max column wise max

[16 16 28 11]
[28 36 35 33]


In [78]:
# replace the last column with sum of all the columns
print(R1[:,-1])
print(R1.sum())
R1[:,3]=R1.sum()
print(R1)

[19 11 33]
308
[[ 21  16  28 308]
 [ 16  36  34 308]
 [ 28  31  35 308]]


In [80]:
# create a matrix (3x4) R1 of random numbers between 10-40

R1 = np.random.randint(10,40,12).reshape(3,4)
print(R1)


[[13 17 11 23]
 [34 23 31 38]
 [33 10 20 31]]


In [84]:
# replace all even elements with nan in R1
R2 = np.where(R1%2==0,np.nan,R1)
print(R2)

[[13. 17. 11. 23.]
 [nan 23. 31. nan]
 [33. nan nan 31.]]


In [86]:
# count number of nan in R1

print(np.sum(np.isnan(R2)))

4


In [91]:
# check output of this code
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
# print(a1)
# print(a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
