<a href="https://colab.research.google.com/github/leangaurav/dsc_weekday_1/blob/master/dsc_weekday_1/Assignments/Pooja/pooja_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:

import numpy as np


In [ ]:
#  create a numpy array of 5 zeros
a = np.zeros(5)
print(a)
#  check datatype, itemsize and shape of above
print(a.dtype)
print(a.itemsize)
print(a.shape)


[0. 0. 0. 0. 0.]
float64
8
(5,)


In [ ]:
# create a numpy array of ones of shape (5,4)
b = np.ones([5,4])

print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# create a matrix of shape 4,5 with numbers from 1-20
x = np.arange(0,20).reshape(4,5)
print(x)
#  multiply all elements of above array by 10
print()
print(x*10)
# print odd elements from array
print()
y = (x[x%2 ==1])
print(y)
#  replace all even elements by their negative
print()
print(np.negative(x))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[[  0  10  20  30  40]
 [ 50  60  70  80  90]
 [100 110 120 130 140]
 [150 160 170 180 190]]

[ 1  3  5  7  9 11 13 15 17 19]

[[  0  -1  -2  -3  -4]
 [ -5  -6  -7  -8  -9]
 [-10 -11 -12 -13 -14]
 [-15 -16 -17 -18 -19]]


In [5]:
# create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
m1 = np.linspace(1,16,16).reshape(4,4)
print(m1)
# create a transpose of above matrix call it M2
m2 = m1.T
print()
print(m2)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]

[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]


In [7]:
# find sum of above matrix M3 = (M1 + M2)
m3 = m1 + m2
print(m3)

[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]


In [13]:
# Find Transpose of M3, Call it MT1. Check if M3 == MT1
# find diffrence of M4 = (M1 - M2)
# Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
mt1 = m3.T
print(mt1)
print()
print(m3 == mt1)
print()
m4 = m1 - m2
print(m4)
print()
mt2 = m4.T
print(mt2)
print()
print(m4 == mt2)
print()
print(m4 == -mt2)

[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]

[[ 0. -3. -6. -9.]
 [ 3.  0. -3. -6.]
 [ 6.  3.  0. -3.]
 [ 9.  6.  3.  0.]]

[[ 0.  3.  6.  9.]
 [-3.  0.  3.  6.]
 [-6. -3.  0.  3.]
 [-9. -6. -3.  0.]]

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [24]:
# create a matrix (3x4) R1 of random numbers between 10-40
a = np.random.randint(10,40,12).reshape(3,4)
print(a)
print()
# find min and max column wise
print(a.min(axis = 0))
print()
print(a.max(axis = 0))
print()
# replace the last column with sum of all the columns
x = a.sum(axis = 0)
print(x)
print()
a[:,3] = x[:3]
print(a)




[[15 18 32 27]
 [26 19 31 25]
 [28 14 34 34]]

[15 14 31 25]

[28 19 34 34]

[69 51 97 86]

[[15 18 32 69]
 [26 19 31 51]
 [28 14 34 97]]


In [39]:
# create a matrix (3x4) R1 of random numbers between 10-40
r1 = np.random.randint(10,40,12).reshape(3,4).astype(float)
print(r1)

# replace all even elements with nan in R1
print()
r1[r1 % 2 == 0] = np.nan
print(r1)

# count number of nan in R1
print()
x = np.isnan(r1).sum()
print(x)

[[16. 30. 34. 21.]
 [32. 22. 19. 19.]
 [27. 17. 36. 26.]]

[[nan nan nan 21.]
 [nan nan 19. 19.]
 [27. 17. nan nan]]

7


In [41]:
# check output of this code
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print()
print(a3)
a3 = np.append(a1,a2, axis = 0)
print()
print(a3)
a3 = np.append(a1,a2, axis = 1)
print()
print(a3)


[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
