## NUMPY
- create a numpy array of 5 zeros.
    - check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative
  
  
  
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns


- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1



- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`


In [1]:
import numpy as np

In [7]:
# create a numpy array of 5 zeros.
a = np.zeros(5, dtype = 'int8')
print(a)

# check datatype, itemsize and shape of above
print(type(a))
print(a.dtype)
print(a.itemsize)
print(a.shape)

[0 0 0 0 0]
<class 'numpy.ndarray'>
int8
1
(5,)


In [11]:
# create a numpy array of ones of shape (5,4)
a = np.ones((5,4), dtype = 'int32')
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [61]:
# create a matrix of shape 4,5 with numbers from 1-20
a = np.arange(1,21)
print(a)
print()
r = a.reshape(4,5)
print(r)
print()

# multiply all elements of above array by 10
print(r*10)
print()

# print odd elements from array
print(a[a%2 != 0])
print()

# replace all even elements by their negative
a[a%2 == 0] *= -1
print(a)
print()

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]

[ 1  3  5  7  9 11 13 15 17 19]

[  1  -2   3  -4   5  -6   7  -8   9 -10  11 -12  13 -14  15 -16  17 -18
  19 -20]



In [38]:
# create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
a = np.linspace(1,16,16, dtype='int8')
print(a)
print()
M1 = a.reshape(4,4)
print(r)
print()

# create a transpose of above matrix call it M2
M2 = M1.T
print(M2)

# find sum of above matrix M3 = (M1 + M2)
M3 = M1 + M2
print(M3)
print()

# Find Transpose of M3, Call it MT1. Check if M3 == MT1
MT1 = M3.T
print(M3 == MT1)
print()

# find diffrence of M4 = (M1 - M2)
M4 = M1 - M2
print(M4)
print()

# Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
MT2 = M4.T
print(MT2)
print()
print(M4 == MT2)
print()
print(M4 == -MT2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]

[[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]

[[ 0  3  6  9]
 [-3  0  3  6]
 [-6 -3  0  3]
 [-9 -6 -3  0]]

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [63]:
# create a matrix (3x4) R1 of random numbers between 10-40
R1 = np.random.randint(10,40,12).reshape(3,4)
print(R1)
print()

# find min and max column wise
print(R1.min(axis = 0))
print()
print(R1.max(axis = 0))
print()

# replace the last column with sum of all the columns
b = R1.sum(axis = 0)
print(s)
print()
R1[:, 3] = b[:3]
print(R1)

[[39 23 39 13]
 [18 30 31 19]
 [38 28 35 18]]

[18 23 31 13]

[39 30 39 19]

[ 95  81 105  50]

[[ 39  23  39  95]
 [ 18  30  31  81]
 [ 38  28  35 105]]


In [70]:
# create a matrix (3x4) R1 of random numbers between 10-40
R1 = np.random.randint(10,40,12).reshape(3,4).astype('float64')
print(R1)
print()

# replace all even elements with nan in R1
R1[R1%2 == 0] = np.nan
print(R1)
print()

# count number of nan in R1
print(np.isnan(R1).sum())

[[19. 12. 10. 13.]
 [28. 25. 16. 31.]
 [11. 11. 19. 25.]]

[[19. nan nan 13.]
 [nan 25. nan 31.]
 [11. 11. 19. 25.]]

4


In [56]:
# check output of this code
a1 = np.arange(1,10).reshape(3,3)
print(a1)
print()
a2 = np.arange(11,20).reshape(3,3)
print(a2)
print()
a3 = np.append(a1,a2)
print(a3)
print()
a3 = np.append(a1,a2, axis = 0)
print(a3)
print()
a3 = np.append(a1,a2, axis = 1)
print(a3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[11 12 13]
 [14 15 16]
 [17 18 19]]

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
