# NUMPY
- create a numpy array of 5 zeros.
    - check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative
  
  
  
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns


- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1



- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`


In [2]:
import numpy as np

In [9]:
# create a numpy array of 5 zeros.
# check datatype, itemsize and shape of above

a= np.zeros(5,dtype='int8')
print(a)
print(a.dtype)
print(a.itemsize)
print(a.shape)

[0 0 0 0 0]
int8
1
(5,)


In [11]:
# create a numpy array of ones of shape (5,4)
a= np.ones((5,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
# create a matrix of shape 4,5 with numbers from 1-20
a= np.arange(1,21).reshape(4,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [18]:
# multiply all elements of above array by 10
b=a*10
print(b)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [22]:
# print odd elements from array
i = (a%2!=0)
print(a[i])
print(b[i])

[ 1  3  5  7  9 11 13 15 17 19]
[ 10  30  50  70  90 110 130 150 170 190]


In [25]:
# replace all even elements by their negative

i = (a%2==0)
a[i]=a[i]*-1
print(a)

[[  1  -2   3  -4   5]
 [ -6   7  -8   9 -10]
 [ 11 -12  13 -14  15]
 [-16  17 -18  19 -20]]


In [36]:
# create a linearly spaced matrix M1 of size 4x4 having values in range 1-16

m1=np.linspace(1,16,16).reshape(4,4)
print(m1)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [37]:
# create a transpose of above matrix call it M2
m2=m1.T
print(m2)

[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]


In [39]:
# find sum of above matrix M3 = (M1 + M2)

m3 =m1+m2
print(m3)

[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]


In [44]:
# Find Transpose of M3, Call it MT1. Check if M3 == MT1

mt1 = m3.T
print(mt1)
print()
print(m3==mt1)

[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [47]:
# find diffrence of M4 = (M1 - M2)

m4= m1-m2
print(m4)

[[ 0. -3. -6. -9.]
 [ 3.  0. -3. -6.]
 [ 6.  3.  0. -3.]
 [ 9.  6.  3.  0.]]


In [49]:
# Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2

mt2= m4.T
print(m4==mt2)
print()
print(m4==-mt2)

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [172]:
# create a matrix (3x4) R1 of random numbers between 10-40
# find min and max column wise
# replace the last column with sum of all the columns
r1= np.random.randint(10,41,size=(3,4))
print(r1)
print()

print(r1.min(axis=0))
print(r1.max(axis=0))
print()

x= r1.sum(axis=0)
r1[:,3]=x[0:3]
print(r1)

[[13 34 25 39]
 [29 30 12 26]
 [27 36 18 10]]

[13 30 12 10]
[29 36 25 39]

[[ 13  34  25  69]
 [ 29  30  12 100]
 [ 27  36  18  55]]


In [157]:
# create a matrix (3x4) R1 of random numbers between 10-40

r1= np.random.randint(10,41,size=12).reshape(3,4)
print(r1)

[[10 21 18 16]
 [36 18 36 22]
 [10 17 15 29]]


In [161]:
# replace all even elements with nan in R1

r2= r1.astype('float32')
i = (r2%2==0)
r2[i] = np.nan
print(r2)


[[nan 21. nan nan]
 [nan nan nan nan]
 [nan 17. 15. 29.]]


In [184]:
# count number of nan in R1

print(np.isnan(r2).sum())

8


In [177]:
# check output of this code

a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
print()
a3 = np.append(a1,a2, axis = 0)
print(a3)
print()
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
