## NUMPY
- create a numpy array of 5 zeros.
    - check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative
  
  
  
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns


- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1



- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`


In [4]:
import numpy as np
z = np.zeros(5)
print(z)
print(z.dtype)
print(z.itemsize)
print(z.shape)

[0. 0. 0. 0. 0.]
float64
8
(5,)


In [7]:
o = np.ones((5,4))
print(o)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
m = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(m)
print(f'shape of the above matrix(m) - {m.shape}')

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
shape of the above matrix(m) - (4, 5)


In [18]:
mul_ten = m*10
print(f'Multiplying all the number with 10:\n {mul_ten}')

Multiplying all the number with 10:
 [[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [21]:
od = (m [m%2 == 1])
print(od)

[ 1  3  5  7  9 11 13 15 17 19]


In [26]:
m[m%2 == 0]*= -1
print(m)

[[  1  -2   3  -4   5]
 [ -6   7  -8   9 -10]
 [ 11 -12  13 -14  15]
 [-16  17 -18  19 -20]]


In [59]:
M1 = np.linspace(1,16, 16)
M1.resize(4,4)
print(M1)
print(M1.shape)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
(4, 4)


In [60]:
M2 = M1.T
print(M2)

[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]


In [61]:
M3 = M1 + M2
print(M3)

[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]


In [64]:
MT1 = M3.T
print(MT1)
print('--'*7)
print(M3)
print('--'*7)
print(MT1 == M3)

[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]
--------------
[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]
--------------
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [65]:
M4 = M1 - M2
print(M4)

[[ 0. -3. -6. -9.]
 [ 3.  0. -3. -6.]
 [ 6.  3.  0. -3.]
 [ 9.  6.  3.  0.]]


In [66]:
MT2 = M4.T
print(MT2)

[[ 0.  3.  6.  9.]
 [-3.  0.  3.  6.]
 [-6. -3.  0.  3.]
 [-9. -6. -3.  0.]]


In [69]:
print(M4)
print('--'*7)
print(MT2)
print('--'*7)
print(M4 == MT2)
print('--'*7)
print(M4 == -MT2)

[[ 0. -3. -6. -9.]
 [ 3.  0. -3. -6.]
 [ 6.  3.  0. -3.]
 [ 9.  6.  3.  0.]]
--------------
[[ 0.  3.  6.  9.]
 [-3.  0.  3.  6.]
 [-6. -3.  0.  3.]
 [-9. -6. -3.  0.]]
--------------
[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]
--------------
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [108]:
R1 = np.random.randint(10, 40, 12).reshape(3, 4)
R1

array([[27, 14, 28, 13],
       [17, 11, 33, 23],
       [10, 35, 17, 32]])

In [109]:
print(R1.min(axis = 0))

[10 11 17 13]


In [110]:
print(R1.max(axis = 0))

[27 35 33 32]


In [111]:
s = R1.sum(axis = 0)
print(s)
print('-'*10)
print(R1)
print('-'*10)
R1[:, 3] = s[:3]
print(R1)

[54 60 78 68]
----------
[[27 14 28 13]
 [17 11 33 23]
 [10 35 17 32]]
----------
[[27 14 28 54]
 [17 11 33 60]
 [10 35 17 78]]


In [145]:
R1 = np.random.randint(10, 40, 12).reshape(3, 4).astype(float) #as we cannot add nan to integers!
print(R1)
print(R1.dtype)

[[22. 15. 11. 30.]
 [16. 33. 26. 18.]
 [15. 22. 29. 39.]]
float64


In [146]:
R1[R1%2 == 0] = np.nan
print(R1)

[[nan 15. 11. nan]
 [nan 33. nan nan]
 [15. nan 29. 39.]]


In [147]:
print(f'Total count of nan in R1 - {(np.isnan(R1)).sum()}')

Total count of nan in R1 - 6


In [154]:
a1 = np.arange(1,10).reshape(3,3)
print(a1)
print(a1.shape)
a2 = np.arange(11,20).reshape(3,3)
print(a2)
print(a2.shape)
a3 = np.append(a1,a2) # append without axis is directly appending like list append.
print(a3)
print(a3.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[[11 12 13]
 [14 15 16]
 [17 18 19]]
(3, 3)
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
(18,)


In [156]:
a3 = np.append(a1,a2, axis = 0) # axis=0 , appends as rows
print(a3)
print(a3.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
(6, 3)


In [155]:
a3 = np.append(a1,a2, axis = 1) # axis=1 , appends as columns
print(a3)
print(a3.shape)

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
(3, 6)
