In [20]:
import numpy as np

In [30]:
#create a numpy array of 5 zeros.

a=np.array([0,0,0,0,0])
print(a)

#check datatype, itemsize and shape of above
print(a.dtype)
print(a.itemsize)
print(a.shape)


[0 0 0 0 0]
int32
4
(5,)


In [43]:
#create a numpy array of ones of shape (5,4)
ar=np.ones([5,4])
print(ar)
print(ar.shape)



[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(5, 4)


In [56]:
#create a matrix of shape 4,5 with numbers from 1-20
mat=np.arange(1,21).reshape(4,5)
print(mat)
print(mat.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
(4, 5)


In [57]:
#multiply all elements of above array by 10
print(mat*10)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [71]:
#print odd elements from array
a = mat [(mat%2==1)]
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


In [74]:
# replace all even elements by their negative

b = mat [(mat%2==0)]
print(-b)

[ -2  -4  -6  -8 -10 -12 -14 -16 -18 -20]


In [194]:
#create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
M1=np.linspace(1,16,16).reshape(4,4)
print(M1)
print(M1.shape)


[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
(4, 4)


In [163]:
#create a transpose of above matrix call it M2
M2=[M1.T]
print(M2)

[array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])]


In [164]:
#find sum of above matrix M3 = (M1 + M2)
M3=M1+M2
print(M3)

[[[ 2  7 12 17]
  [ 7 12 17 22]
  [12 17 22 27]
  [17 22 27 32]]]


In [202]:
#Find Transpose of M3, Call it MT1. Check if M3 == MT1
MT1=[M3.T]
print(MT1)
a= M3== MT1

if a.all()==True:
    print('same')
else:
    print('not same')
    

[array([[[ 2],
        [ 7],
        [12],
        [17]],

       [[ 7],
        [12],
        [17],
        [22]],

       [[12],
        [17],
        [22],
        [27]],

       [[17],
        [22],
        [27],
        [32]]])]
not same


In [177]:
#find diffrence of M4 = (M1 - M2)
M4 = (M1 - M2)
print(M4)

[[[ 0 -3 -6 -9]
  [ 3  0 -3 -6]
  [ 6  3  0 -3]
  [ 9  6  3  0]]]


In [208]:
#Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
MT2=M4.T
print(MT2)
b= M4==-MT2
if b.all()==True:
        print('same')
else:
        print('not same')
    
   

[[[ 0]
  [ 3]
  [ 6]
  [ 9]]

 [[-3]
  [ 0]
  [ 3]
  [ 6]]

 [[-6]
  [-3]
  [ 0]
  [ 3]]

 [[-9]
  [-6]
  [-3]
  [ 0]]]
not same


In [210]:
#create a matrix (3x4) R1 of random numbers between 10-40
mat1=np.random.randint(10,40,12).reshape(3,4)
print(mat1)


[[37 25 27 27]
 [27 20 30 29]
 [21 19 21 18]]


In [217]:
#find min and max column wise
print(mat1.min(axis=0))
print(mat1.max(axis=0))

[21 19 21 18]
[37 25 30 29]


In [243]:
#replace the last column with sum of all the columns
#New Random matrix
mat2=np.random.randint(10,40,12).reshape(3,4)
print(mat2)
print()

#Accessing the last column : postive index 3; negative index -1
print(mat2[:,3])
print()

#sum of all columns is eventually sum of all elements in matrix
print(mat2.sum())
print()

#Replacing last column with sum value obtained above
mat2[:,3]=mat2.sum()
print(mat2)


[[13 13 36 30]
 [12 37 39 13]
 [38 39 33 15]]

[30 13 15]

318

[[ 13  13  36 318]
 [ 12  37  39 318]
 [ 38  39  33 318]]


In [265]:
#create a matrix (3x4) R1 of random numbers between 10-40
R1=np.random.randint(10,40,12).reshape(3,4)
print(R1)
print()
#replace all even elements with nan in R1
R2= np.where([R1%2==0],np.nan,R1)
print(R2)

    


[[14 34 14 20]
 [12 27 11 32]
 [24 19 15 13]]

[[[nan nan nan nan]
  [nan 27. 11. nan]
  [nan 19. 15. 13.]]]


In [279]:
#count number of nan in R1
a=np.sum(np.isnan(R2))
print(a)

7


In [286]:
#check output of this code
a1 = np.arange(1,10).reshape(3,3) 
print(a1)
a2 = np.arange(11,20).reshape(3,3)
print(a2)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1) 
# print(a3)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
